# Nome da aplicação
spring.application.name=E-commerce API

# Configuração do H2 em memória (para testes)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Mostrar SQL no terminal
spring.jpa.show-sql=true

# Criar as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=create

# Dialeto do H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Console do H2 ativado
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Evita erros de case-sensitive em nomes de tabela
spring.jpa.properties.hibernate.globally_quoted_identifiers=true